# This is a basic workflow to help you get started with Actions

name: Terraform CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
       
      # Authentication  
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP_CREDENTIALS }}

      # terraform installation
      - name: terraform setup
        uses: hashicorp/setup-terraform@v3
        
      
      # install check
      - name: Check terraform version
        shell: pwsh
        run: |
          
          $env:Path = "${env:TERRAFORM_CLI_PATH};$env:Path"
          terraform --version
          

      # terraform init
      - name: terraform init
        working-directory: terraform/dev
        run: |
          terraform init -input=false -no-color
      
      # terraform plan
      - name: chk directory
        shell: pwsh
        working-directory: terraform/dev
        run: |
          Get-ChildItem -Recurse
         

      - name: terraform plan (save tfplan)
        working-directory: terraform/dev
        run: |
          terraform plan -out=tfplan

      - name: terraform plan (display tfplan)
        working-directory: terraform/dev
        run: |
          terraform show -no-color tfplan
          # Optional: Check if the plan found any changes
          if ($LASTEXITCODE -ne 0) {
              Write-Host "Terraform plan succeeded but found no changes (0 to add, 0 to change, 0 to destroy)."
          }

      # terraform apply
      - name: terraform apply
        working-directory: terraform/dev
        run: |
          terraform apply -auto-approve tfplan



      
          
